# Generated by Django 6.0.6 on 2026-06-23 21:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Customer Profile'},
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='billing.customer'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='payment_terms',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_15', '15 days'), ('credit_30', '30 days'), ('credit_60', '60 days')], default='cash', max_length=15),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='taxpayer_type',
            field=models.CharField(choices=[('final', 'Final Consumer'), ('ruc', 'RUC'), ('rise', 'RISE')], default='final', max_length=10),
        ),
    ]
