# Generated by Django 6.0.6 on 2026-06-24 22:11

from django.db import migrations, models


def assign_invoice_numbers(apps, schema_editor):
    Invoice = apps.get_model('billing', 'Invoice')
    for i, inv in enumerate(Invoice.objects.filter(is_active=True).order_by('id'), 1):
        inv.number = i
        inv.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='N° Factura'),
        ),
        migrations.RunPython(assign_invoice_numbers, migrations.RunPython.noop),
    ]
