# Generated by Django 6.0.6 on 2026-06-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_city_created_at_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, verbose_name='RUC'),
        ),
    ]
