# Generated by Django 6.0.6 on 2026-07-09 14:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_desc_to_group_ruc_to_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada')], default='pagada', max_length=10, verbose_name='Estado de Cobro'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo Pendiente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tipo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10, verbose_name='Tipo de Pago'),
        ),
    ]
