# Generated by Django 6.0.6 on 2026-07-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_estado_invoice_saldo_invoice_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_generic',
            field=models.BooleanField(default=False, verbose_name='Consumidor Final Genérico'),
        ),
    ]
