# Generated by Django 6.0.6 on 2026-07-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_seed_consumidor_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ambiente',
            field=models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1, verbose_name='Ambiente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=49, verbose_name='Clave de Acceso'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establecimiento',
            field=models.CharField(default='001', max_length=3, verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='estado_sri',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizada', 'Autorizada'), ('no_autorizada', 'No autorizada')], default='pendiente', max_length=15, verbose_name='Estado SRI'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='numero_autorizacion',
            field=models.CharField(blank=True, max_length=49, verbose_name='N° Autorización'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='punto_emision',
            field=models.CharField(default='001', max_length=3, verbose_name='Punto de Emisión'),
        ),
    ]
