# Generated by Django 6.0.6 on 2026-07-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_ambiente_invoice_clave_acceso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'permissions': [('can_export', 'Puede exportar reportes a PDF/Excel')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
