# Generated by Django 6.0.6 on 2026-07-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_invoice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='razon_social_emisor',
            field=models.CharField(blank=True, max_length=300, verbose_name='Razón Social Emisor'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ruc_emisor',
            field=models.CharField(blank=True, max_length=13, verbose_name='RUC Emisor'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='xml_autorizado',
            field=models.TextField(blank=True, verbose_name='XML autorizado / firmado'),
        ),
    ]
