# Generated by Django 6.0.6 on 2026-07-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0007_invoice_estado_invoice_saldo_invoice_tipo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Pago')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Abonado')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='billing.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Cobro de Factura',
                'verbose_name_plural': 'Cobros de Facturas',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
