# Generated by Django 6.0.6 on 2026-07-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_cobrofactura_metodo_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobrofactura',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='cobrofactura',
            name='paypal_order_id',
        ),
    ]
