# Generated by Django 6.0.6 on 2026-07-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_remove_cobrofactura_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrofactura',
            name='metodo_pago',
            field=models.CharField(choices=[('manual', 'Manual'), ('paypal', 'PayPal')], default='manual', max_length=10, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='cobrofactura',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID de Orden PayPal'),
        ),
    ]
