"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l_x-r2af20^&t9&e&07q9=y@au&5xdsr^&0ij(nz$dmmno^%*l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# '*' para que el sistema sea accesible desde otras computadoras de la red
# (ej. para que el enlace de la factura en el correo funcione en otro equipo).
# Solo recomendable en desarrollo/pruebas, no en producción real.
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'billing',
    'purchasing',
    'cobros',
    'pagos',
    'security',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cobros.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Autenticación: se usa AllowAllUsersModelBackend (en vez del ModelBackend por
# defecto) para que authenticate() no rechace silenciosamente a los usuarios
# inactivos — así RoleAwareAuthenticationForm.confirm_login_allowed() puede
# mostrar el mensaje específico de "cuenta inactiva" en vez del genérico de
# credenciales incorrectas.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.AllowAllUsersModelBackend',
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Email (envío de facturas al cliente por correo)
# ─────────────────────────────────────────────────────────────────────────────
# 1. Activa la verificación en 2 pasos en tu cuenta de Gmail.
# 2. Genera una "contraseña de aplicación" en https://myaccount.google.com/apppasswords
#    (elige app "Correo", dispositivo "Otro", y copia el código de 16 caracteres).
# 3. Reemplaza las dos líneas de abajo con tu correo y esa contraseña.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mmonserratem4@unemi.edu.ec'          # <-- reemplaza con tu Gmail
EMAIL_HOST_PASSWORD = 'rfhw muap qpmo njgu'      # <-- contraseña de aplicación (16 caracteres)
DEFAULT_FROM_EMAIL = f'"TecnoStock S.A." <{EMAIL_HOST_USER}>'


# Microservicio de pagos con PayPal
# ─────────────────────────────────────────────────────────────────────────────
# El cobro con PayPal NO se hace directo desde Django: este apunta a un
# microservicio aparte (carpeta `paypal_service/`, hecho en Flask) que es
# quien realmente habla con la API de PayPal (el Client Secret vive SOLO
# ahí). Antes de usar el botón de PayPal, corre ese servicio en otra
# terminal:
#     .\venv\Scripts\python.exe paypal_service\app.py
# (queda escuchando en el puerto indicado abajo).
PAYPAL_SERVICE_URL = 'http://localhost:5001'

# El botón de PayPal se dibuja en el navegador con el SDK oficial de PayPal,
# que necesita el Client ID (es público, no el Secret) de la misma app de
# developer.paypal.com que configuraste en paypal_service/app.py.
PAYPAL_CLIENT_ID = 'AfeLi2Q6OfDSxMCvEnwwObOnuPfK4XDnWC8mLSDsSPXLuskh_5HF9TORMEefmqM5tk0KOho3xHhN8nOd'  # <-- reemplaza con tu Client ID

# Microservicio de consulta al SRI (catastro de contribuyentes)
# ─────────────────────────────────────────────────────────────────────────────
# Django NO consulta el SRI directamente. Apunta a sri_service/ (Flask):
#     python sri_service\app.py
# Escucha en el puerto 5002.
SRI_SERVICE_URL = 'http://localhost:5002'

# Microservicio de facturación electrónica SRI — SOLO ambiente de PRUEBAS (celcer)
# ─────────────────────────────────────────────────────────────────────────────
# Flask (API) + Node solo para firmar XAdES. El .p12 se pide en un modal por
# cada envío y NO se guarda. NO usa producción.
#     pip install -r sri_facturacion_service\requirements.txt
#     cd sri_facturacion_service && npm install   (una vez, para node-forge)
#     python sri_facturacion_service\app.py
# Puerto 5003.
SRI_FACTURACION_SERVICE_URL = 'http://localhost:5003'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

LOGIN_URL = '/accounts/select-role/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/select-role/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django usa tags "error"/"success"; Bootstrap 5 espera "danger"/"success"
MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}

