# Generated by Django 6.0.6 on 2026-06-24 22:11

from django.db import migrations, models


def assign_purchase_numbers(apps, schema_editor):
    Purchase = apps.get_model('purchasing', 'Purchase')
    for i, p in enumerate(Purchase.objects.filter(is_active=True).order_by('id'), 1):
        p.number = i
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='N° Compra'),
        ),
        migrations.RunPython(assign_purchase_numbers, migrations.RunPython.noop),
    ]
