# Generated by Django 6.0.6 on 2026-07-11 06:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_add_number_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada')], default='pagada', max_length=10, verbose_name='Estado de Pago'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo Pendiente'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tipo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10, verbose_name='Tipo de Pago'),
        ),
    ]
